version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - node/install-packages:
          app-dir: app 
          cache-path: ~/.npm 
          cache-version: v1 
          override-ci-command: npm install -g yo generator-hubot 
workflows:
  example-workflow:
    jobs:
      - example-job